site_name: Google Trends Collection Framework
site_url: https://dissc-yale.github.io/gtrends_collection
theme:
  name: material
  font:
    text: Nunito Sans
    code: SFMono-Regular
  palette:
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb
        name: Switch to light theme
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark theme
  features:
    - content.code.copy
  favicon: assets/icon.svg
  logo: assets/logo.png
copyright: <a href="https://dissc.yale.edu/">&#10140; Data Intensive Social Science Center</a>
repo_url: https://github.com/dissc-yale/gtrends_collection
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
docs_dir: 'docs_source'
site_dir: 'docs'
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
nav:
  - Home: README.md
  - Data.md
  - Functions:
      - functions/Collector.md
      - functions/dataset.md
      - functions/utils.md
  - Framework.md
  - Test Coverage: coverage/index.html
